In [19]:
import json
import os
import pathlib

In [20]:
preface = """This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg License included with this ebook or online
at www.gutenberg.org. If you are not located in the United States,
you will have to check the laws of the country where you are located
before using this eBook."""

In [26]:
all_books = os.listdir('cache/')
print(len(all_books))
for i, book in enumerate(all_books):
    with open(pathlib.Path('cache', book, 'content.txt')) as file:
        content =file.read()
    if preface not in content:
        print(i, book)
        # print(content)
    # if book in ['6557', '8631', '9427']:
    # break

31
13 6557
15 8631
17 9427


In this random list of 31 Gutenberg project text files, only three books: 6557, 8631, and 9427 don't have the above preface in their content, because they happen to be Audiobooks. Hence, we deduce that all EPUBs contain the above preface and can be safely used to cut down the length of the text file without compromising the book content.